openapi: "3.0.3"
info:
  title: "saving_management API"
  description: "saving_management API"
  version: "1.0.0"
servers:
  - url: "https://saving_management"
paths:
  /v1/transaction/save:
    post:
      summary: "POST v1/transaction/save"
      operationId: "save"
      requestBody:
        content:
          application/json:
            schema:
              type: "string"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "object"
  /v1/customer/transactions:
    get:
      summary: "GET v1/customer/transactions"
      operationId: "getTransactionsPerCustomer"
      parameters:
        - name: "customerId"
          in: "query"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "object"